version: '3'
services:
  spring-blue:
    image: msp_back:blue
    container_name: spring-container-blue
    build:
      context: backend
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/moonspoon
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    depends_on:
#      - mysql
    networks:
      - app-network
    env_file:
      - .env

  spring-green:
    image: msp_back:green
    container_name: spring-container-green
    build:
      context: backend
      dockerfile: backend/Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/moonspoon
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    depends_on:
#      - mysql
    networks:
      - app-network
    env_file:
      - .env

#  vue-blue:
#    image: msp_front:blue
#    container_name: vue-container-blue
#    build:
#      context: ./vue-cli
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    networks:
#      - app-network
#
#  vue-green:
#    image: msp_front:green
#    container_name: vue-container-green
#    build:
#      context: ./vue-cli
#      dockerfile: Dockerfile
#    ports:
#      - "3001:3000"
#    networks:
#      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default:/etc/nginx/conf.d/default.conf  # default 설정 파일 추가
    depends_on:
      - spring-blue
      - spring-green
#      - vue-blue
#      - vue-green
    networks:
      - app-network

#  mysql:
#    image: mysql:8.0
#    container_name: mysql-container
#    environment:
#      MYSQL_ROOT_PASSWORD: ${RDS_PASSWORD}
#      MYSQL_DATABASE: ${RDS_DB_NAME}
#    ports:
#      - "3306:3306"
#    networks:
#      - app-network
#    env_file:
#      - .env

networks:
  app-network:
    driver: bridge
