FROM nginx:latest

RUN apt-get update && apt-get install -y wget unzip

# GeoIP 데이터베이스 다운로드 및 설치
RUN mkdir -p /usr/share/GeoIP \
    && wget https://dl.miyuru.lk/geoip/maxmind/country/maxmind4.dat.gz \
    && gunzip maxmind4.dat.gz \
    && mv maxmind4.dat /usr/share/GeoIP/GeoIP.dat

RUN apt-get update

# Nginx 모듈 설치 (GeoIP 모듈 포함)
RUN apt-get install -y geoip-database

COPY GeoIP.dat /usr/share/GeoIP/

# Nginx 설정 파일 복사
COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
