#서버 재시작시 세션 초기화
server:
  servlet:
    session:
      persistent: false

spring:
  jwt:
    secret: testzzcxdfgbsfgSecretKey2adasd024202asdsad4testasdasdSecradazxcetKey2024asdasdsa2024te
    expiration: 86400000  # 1 day in milliseconds

  mvc:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moonspoon?serverTimezone=Asia/Seoul
    username: seungyoung
    password: lsy991122

  #    url: jdbc:h2:tcp://localhost/~/moonspoon
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 30
        order_updates: true
logging:
  level:
    org.hibernate.SQL: debug
