#서버 재시작시 세션 초기화
server:
  servlet:
    session:
      persistent: false

spring:
  config:
    activate:
      on-profile: local
  jwt:
    secret: testzzcxdfgbsfgSecretKey2adasd024202asdsad4testasdasdSecradazxcetKey2024asdasdsa2024te
    expiration: 86400000  # 1 day in milliseconds

  datasource:
    url: jdbc:mysql://localhost:3306/moonspoon
    username: seungyoung
    password: lsy991122

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 30
        order_updates: true
logging:
  level:
    org.hibernate.SQL: debug
