name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'Moon-Spoon/vue-cli/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Moon-Spoon/vue-cli/**'

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: Build and test frontend
      run: |
        cd frontend
        npm install
        npm run test
        npm run build
    
    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        cd frontend
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build -t $DOCKER_USERNAME/frontend:latest .
        docker push $DOCKER_USERNAME/frontend:latest
    
    - name: Deploy to AWS S3 and invalidate CloudFront
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-1
        aws s3 sync frontend/dist s3://your-frontend-bucket --delete
        aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
