name: moonspoon CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Build and test backend
        run: |
          ./gradlew build test

      - name: Build and test frontend
        run: |
          cd vue-cli
          npm install
          npm run test:unit

      - name: Build and push Docker images
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          
          # Backend
          cd Moon-Spoon
          docker build -t $DOCKER_USERNAME/msp_back:blue .
          docker push $DOCKER_USERNAME/msp_back:blue
          
          # Frontend
          cd ../vue-cli
          docker build -t $DOCKER_USERNAME/msp_front:blue .
          docker push $DOCKER_USERNAME/msp_front:blue

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose pull spring-blue vue-blue
            docker-compose up -d spring-blue vue-blue
            sleep 30
            if docker exec spring-container-blue curl -f http://localhost:8080/health && \
               docker exec vue-container-blue curl -f http://localhost:3000; then
              # Update Nginx to route to blue versions
              sed -i 's/spring-green/spring-blue/g' /path/to/nginx.conf
              sed -i 's/vue-green/vue-blue/g' /path/to/nginx.conf
              docker-compose up -d --no-deps nginx
              echo "Deployment successful, updated nginx to route to blue versions"
            else
              docker-compose stop spring-blue vue-blue
              echo "Deployment failed, rolling back"
            fi

      - name: Cleanup old deployments
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose stop spring-green vue-green
            docker-compose rm -f spring-green vue-green
            docker image prune -af